# Site settings
title: Michael Fiebelkorns Blog
description: 'Infrastructure Engineer focused on DevOps and Automation in a mostly Windows World'
url: 'http://joshgerdes.com/jekyll-uno'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Michael Fiebelkorn'
  email: michael.fiebelkorn@live.com
  twitter_username: mfiebs
  facebook_username: michael.fiebelkorn.7
  github_username:  mfiebelkorn
  linkedin_username:  michaelfiebelkorn

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
